const REQUEST = "REQUEST";
const FAILURE = "FAILURE";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGOUT = "LOGOUT";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export { REQUEST, FAILURE, LOGIN_SUCCESS, LOGOUT, REGISTER_SUCCESS };
